In [6]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
perf = pd.read_csv('performances.csv')
perf = perf.drop(columns=['Unnamed: 0'])
perf

,program_used,dataset_used,success,answers,time
0,problem,B with zeros,True,"['selgene(lgals1)', 'selgene(aes)', 'selgene(s...",2.334
1,v10.2,B with zeros,False,[],0.072
2,v10.2noparents,B with zeros,True,"['affinity(e510933,e5121033)', 'affinity(e5109...",0.111
3,problem,C with zeros,True,"['selgene(lgals1)', 'selgene(aes)', 'selgene(e...",95.560
4,v10.2,C with zeros,True,"['affinity(e510943,e5373235)', 'selgene(igf2)'...",0.444
5,v10.2noparents,C with zeros,True,"['affinity(e510933,e5121033)', 'affinity(e5109...",0.581
6,problem,B without zeros,True,"['selgene(lgals1)', 'selgene(egr1)', 'selgene(...",1.220
7,v10.2,B without zeros,False,[],0.046
8,v10.2noparents,B without zeros,True,"['selgene(egr1)', 'selgene(foxa1)', 'affinity(...",0.055
9,problem,C without zeros,True,"['selgene(aes)', 'selgene(egr1)', 'selgene(usf...",147.000
10,v10.2,C without zeros,True,"['selgene(tgfb1)', 'selgene(gli1)', 'selgene(c...",0.311
11,v10.2noparents,C without zeros,True,"['affinity(0,3)', 'affinity(1,4)', 'affinity(3...",0.472

In [29]:
perf[['program_used', 'dataset_used', 'time']].groupby(['program_used','dataset_used']).mean()

                                   time
program_used   dataset_used
problem        B with zeros       2.334
               B without zeros    1.220
               C with zeros      95.560
               C without zeros  147.000
v10.2          B with zeros       0.072
               B without zeros    0.046
               C with zeros       0.444
               C without zeros    0.311
v10.2noparents B with zeros       0.111
               B without zeros    0.055
               C with zeros       0.581
               C without zeros    0.472